// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using StudentGrade.Core.Models;

namespace StudentGrade.Infrastructure.Data;

public partial class StudentGradeContext : DbContext
{
    public StudentGradeContext(DbContextOptions<StudentGradeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AichatHistory> AichatHistories { get; set; }

    public virtual DbSet<Assessment> Assessments { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<ImportHistory> ImportHistories { get; set; }

    public virtual DbSet<Fgexport> Fgexports { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<StudentScore> StudentScores { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AichatHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AIChatHi__3214EC07FEEC9772");

            entity.ToTable("AIChatHistories");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.AskedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Question).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AichatHistories)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_AIChatHistories_Users");
        });

        modelBuilder.Entity<Assessment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Assessme__3214EC076B4659BD");

            entity.HasIndex(e => new { e.AssessmentCode, e.SubjectId }, "UQ__Assessment_Code_Subject").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.AssessmentCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AssessmentName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Subject).WithMany(p => p.Assessments)
                .HasForeignKey(d => d.SubjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Assessments_Subjects");
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AuditLog__3214EC07EFC5399F");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_AuditLogs_Users");
        });

        modelBuilder.Entity<ImportHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ImportHi__3214EC077F18FA3B");

            entity.HasIndex(e => e.ImportedAt, "IX_ImportHistories_ImportedAt");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ImportedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.ImportedByNavigation).WithMany(p => p.ImportHistories)
                .HasForeignKey(d => d.ImportedBy)
                .HasConstraintName("FK_ImportHistories_Users");
        });

        modelBuilder.Entity<Fgexport>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PMGExpor__3214EC07C5ED6A96");

            entity.ToTable("FGExports");

            entity.HasIndex(e => e.ExportedAt, "IX_FGExports_ExportedAt");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.ExportedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.ExportedByNavigation).WithMany(p => p.Fgexports)
                .HasForeignKey(d => d.ExportedBy)
                .HasConstraintName("FK_FGExports_Users");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Subjects");

            entity.HasIndex(e => e.SubjectCode, "UQ__Subjects__SubjectCode").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.SubjectCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Students__3214EC077F4D1606");

            entity.HasIndex(e => e.RollNumber, "IX_Students_RollNumber");

            entity.HasIndex(e => e.RollNumber, "UQ__Students__E9F06F16CA514B74").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.MemberCode).HasMaxLength(50);
            entity.Property(e => e.RollNumber)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<StudentScore>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StudentS__3214EC07BA001336");

            entity.HasIndex(e => e.AssessmentId, "IX_StudentScores_AssessmentId");

            entity.HasIndex(e => e.StudentId, "IX_StudentScores_StudentId");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Semester).IsRequired().HasMaxLength(50);
            entity.Property(e => e.ClassName).IsRequired().HasMaxLength(100);
            entity.Property(e => e.Score).HasPrecision(5, 2);

            entity.HasOne(d => d.Assessment).WithMany(p => p.StudentScores)
                .HasForeignKey(d => d.AssessmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentScores_Assessments");

            entity.HasOne(d => d.ImportedFile).WithMany(p => p.StudentScores)
                .HasForeignKey(d => d.ImportedFileId)
                .HasConstraintName("FK_StudentScores_ImportHistories");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentScores)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentScores_Students");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC0773D05D9B");

            entity.HasIndex(e => e.Username, "UQ__Users__536C85E42BC6DF6C").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PasswordHash).IsRequired();
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Role)
            .IsRequired()
            .HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}