// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentGrade.Core.Models;

public partial class AichatHistory
{
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public DateTime AskedAt { get; set; }

    public virtual User User { get; set; }
}