// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentGrade.Core.Models;

public partial class Assessment
{
    public Guid Id { get; set; }

    public string AssessmentCode { get; set; }

    public string AssessmentName { get; set; }

    public double Weight { get; set; }

    public bool IsResitSupported { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<StudentScore> StudentScores { get; set; } = new List<StudentScore>();
}