// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentGrade.Core.Models;

public partial class Pmgexport
{
    public Guid Id { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public Guid? ExportedBy { get; set; }

    public DateTime ExportedAt { get; set; }

    public int TotalStudents { get; set; }

    public virtual User ExportedByNavigation { get; set; }
}