// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentGrade.Core.Models;

public partial class Student
{
    public Guid Id { get; set; }

    public string RollNumber { get; set; }

    public string MemberCode { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<StudentScore> StudentScores { get; set; } = new List<StudentScore>();
}