// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentGrade.Core.Models;

public partial class StudentScore
{
    public Guid Id { get; set; }

    public Guid StudentId { get; set; }

    public Guid AssessmentId { get; set; }

    public double? Score { get; set; }

    public string Comment { get; set; }

    public bool IsResit { get; set; }

    public DateTime? ExamDate { get; set; }

    public string ExamNote { get; set; }

    public Guid? ImportedFileId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Assessment Assessment { get; set; }

    public virtual ImportHistory ImportedFile { get; set; }

    public virtual Student Student { get; set; }
}