// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentGrade.Core.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<AichatHistory> AichatHistories { get; set; } = new List<AichatHistory>();

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<ImportHistory> ImportHistories { get; set; } = new List<ImportHistory>();

    public virtual ICollection<Pmgexport> Pmgexports { get; set; } = new List<Pmgexport>();
}