// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentGrade.Infrastructure.Data;

#nullable disable

namespace StudentGrade.Infrastructure.Migrations
{
    [DbContext(typeof(StudentGradeContext))]
    [Migration("20260515152127_UpdateScoreToDecimal")]
    partial class UpdateScoreToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentGrade.Core.Models.AichatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AskedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__AIChatHi__3214EC07FEEC9772");

                    b.HasIndex("UserId");

                    b.ToTable("AIChatHistories", (string)null);
                });

            modelBuilder.Entity("StudentGrade.Core.Models.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AssessmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsResitSupported")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Assessme__3214EC076B4659BD");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "AssessmentCode", "SubjectId" }, "UQ__Assessment_Code_Subject")
                        .IsUnique();

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC07EFC5399F");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.Fgexport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("ExportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("ExportedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PMGExpor__3214EC07C5ED6A96");

                    b.HasIndex("ExportedBy");

                    b.HasIndex(new[] { "ExportedAt" }, "IX_FGExports_ExportedAt");

                    b.ToTable("FGExports", (string)null);
                });

            modelBuilder.Entity("StudentGrade.Core.Models.ImportHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("FailedRows")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("ImportedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SuccessRows")
                        .HasColumnType("int");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ImportHi__3214EC077F18FA3B");

                    b.HasIndex("ImportedBy");

                    b.HasIndex(new[] { "ImportedAt" }, "IX_ImportHistories_ImportedAt");

                    b.ToTable("ImportHistories");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MemberCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Students__3214EC077F4D1606");

                    b.HasIndex(new[] { "RollNumber" }, "IX_Students_RollNumber");

                    b.HasIndex(new[] { "RollNumber" }, "UQ__Students__E9F06F16CA514B74")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.StudentScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ImportedFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsResit")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__StudentS__3214EC07BA001336");

                    b.HasIndex("ImportedFileId");

                    b.HasIndex(new[] { "AssessmentId" }, "IX_StudentScores_AssessmentId");

                    b.HasIndex(new[] { "StudentId" }, "IX_StudentScores_StudentId");

                    b.ToTable("StudentScores");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Subjects");

                    b.HasIndex(new[] { "SubjectCode" }, "UQ__Subjects__SubjectCode")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0773D05D9B");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E42BC6DF6C")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.AichatHistory", b =>
                {
                    b.HasOne("StudentGrade.Core.Models.User", "User")
                        .WithMany("AichatHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AIChatHistories_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.Assessment", b =>
                {
                    b.HasOne("StudentGrade.Core.Models.Subject", "Subject")
                        .WithMany("Assessments")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Assessments_Subjects");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.AuditLog", b =>
                {
                    b.HasOne("StudentGrade.Core.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.Fgexport", b =>
                {
                    b.HasOne("StudentGrade.Core.Models.User", "ExportedByNavigation")
                        .WithMany("Fgexports")
                        .HasForeignKey("ExportedBy")
                        .HasConstraintName("FK_FGExports_Users");

                    b.Navigation("ExportedByNavigation");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.ImportHistory", b =>
                {
                    b.HasOne("StudentGrade.Core.Models.User", "ImportedByNavigation")
                        .WithMany("ImportHistories")
                        .HasForeignKey("ImportedBy")
                        .HasConstraintName("FK_ImportHistories_Users");

                    b.Navigation("ImportedByNavigation");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.StudentScore", b =>
                {
                    b.HasOne("StudentGrade.Core.Models.Assessment", "Assessment")
                        .WithMany("StudentScores")
                        .HasForeignKey("AssessmentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentScores_Assessments");

                    b.HasOne("StudentGrade.Core.Models.ImportHistory", "ImportedFile")
                        .WithMany("StudentScores")
                        .HasForeignKey("ImportedFileId")
                        .HasConstraintName("FK_StudentScores_ImportHistories");

                    b.HasOne("StudentGrade.Core.Models.Student", "Student")
                        .WithMany("StudentScores")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentScores_Students");

                    b.Navigation("Assessment");

                    b.Navigation("ImportedFile");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.Assessment", b =>
                {
                    b.Navigation("StudentScores");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.ImportHistory", b =>
                {
                    b.Navigation("StudentScores");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.Student", b =>
                {
                    b.Navigation("StudentScores");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.Subject", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("StudentGrade.Core.Models.User", b =>
                {
                    b.Navigation("AichatHistories");

                    b.Navigation("AuditLogs");

                    b.Navigation("Fgexports");

                    b.Navigation("ImportHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
